services:
  clickstack:
    image: clickhouse/clickstack-all-in-one:latest
    container_name: root-cause-clickstack
    ports:
      - "8080:8080"
      - "8123:8123"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - clickstack_data:/var/lib/clickhouse

volumes:
  clickstack_data:
